#define LUA_FUNCTIONS(definelfunc) \
	definelfunc(luaL_openlibs) \
	definelfunc(luaL_newstate) \
	definelfunc(luaL_loadbuffer) \
	definelfunc(lua_tolstring) \
	definelfunc(lua_pushvalue) \
	definelfunc(lua_gettop) \
	definelfunc(lua_atpanic) \
	definelfunc(lua_call) \
	definelfunc(lua_setfield) \
	definelfunc(lua_pushcclosure) \
	definelfunc(lua_settop) \
	definelfunc(lua_rawgeti) \
	definelfunc(lua_type) \
	definelfunc(lua_pushboolean) \
	definelfunc(lua_toboolean) \
	definelfunc(lua_pushnil) \
	definelfunc(lua_pushnumber) \
	definelfunc(lua_tonumber) \
	definelfunc(lua_pushlstring) \
	definelfunc(lua_tocfunction) \
	definelfunc(lua_touserdata) \
	definelfunc(lua_newuserdata) \
	definelfunc(lua_next) \
	definelfunc(lua_createtable) \
	definelfunc(lua_settable) \
	definelfunc(lua_topointer) \
	definelfunc(lua_setmetatable) \
	definelfunc(luaL_ref) \
	definelfunc(lua_gettable) \
	definelfunc(lua_remove) \
	definelfunc(lua_pcall) \
	definelfunc(lua_insert) \
	definelfunc(lua_getmetatable) \
	definelfunc(lua_replace) \
	definelfunc(lua_sethook) \
	definelfunc(lua_gethook) \
	definelfunc(lua_gethookcount) \
	definelfunc(lua_gethookmask)
	